/**
 * API Key Authentication Middleware
 *
 * Protects the proxy endpoints with a Bearer token (OpenAI style).
 * Configure via PROXY_API_KEY environment variable.
 *
 * Behavior:
 * - If PROXY_API_KEY is not set, a key is loaded from PROXY_API_KEY_FILE
 *   (default ~/.claude-max-api-proxy/api-key). If that file does not exist,
 *   a secure random key is generated and written there with mode 0600, so it
 *   stays stable across restarts and never has to be printed to the logs.
 * - Set PROXY_API_KEY=off to explicitly disable authentication
 *   (only recommended for local development).
 * - /health is always public so uptime checks keep working.
 */

import type { Request, Response, NextFunction } from "express";
import { randomBytes, timingSafeEqual } from "crypto";
import { mkdirSync, readFileSync, writeFileSync } from "fs";
import { homedir } from "os";
import path from "path";

export interface ApiKeyStatus {
  enabled: boolean;
  /** True when the key was generated by this call (first run) */
  generated: boolean;
  key: string | null;
  /** File the key was loaded from / written to, when not taken from env */
  keyFile: string | null;
}

let configuredKey: string | null = null;
let authEnabled = false;
let apiKeyStatus: ApiKeyStatus | null = null;

function defaultKeyFile(): string {
  return (
    process.env.PROXY_API_KEY_FILE ||
    path.join(homedir(), ".claude-max-api-proxy", "api-key")
  );
}

function loadOrCreateKeyFile(file: string): { key: string; generated: boolean } {
  try {
    const existing = readFileSync(file, "utf8").trim();
    if (existing) return { key: existing, generated: false };
  } catch {
    // missing or unreadable - generate below
  }
  const key = `sk-proxy-${randomBytes(24).toString("hex")}`;
  mkdirSync(path.dirname(file), { recursive: true, mode: 0o700 });
  // "wx" fails if another process created the file first; re-read theirs then
  try {
    writeFileSync(file, key + "\n", { mode: 0o600, flag: "wx" });
  } catch {
    const theirs = readFileSync(file, "utf8").trim();
    if (!theirs) {
      // Fail closed: an empty key file must never mean "no auth"
      throw new Error(
        `API key file ${file} exists but is empty - delete it to generate a new key, or set PROXY_API_KEY`
      );
    }
    return { key: theirs, generated: false };
  }
  return { key, generated: true };
}

/**
 * Initialize the API key from the environment (or the key file).
 * Idempotent: every server entry point calls it, only the first call counts.
 * Returns a status object so the caller can log what happened.
 */
export function initApiKey(): ApiKeyStatus {
  if (apiKeyStatus) return apiKeyStatus;

  const raw = process.env.PROXY_API_KEY?.trim();

  if (raw && raw.toLowerCase() === "off") {
    configuredKey = null;
    authEnabled = false;
    apiKeyStatus = { enabled: false, generated: false, key: null, keyFile: null };
  } else if (raw) {
    configuredKey = raw;
    authEnabled = true;
    apiKeyStatus = { enabled: true, generated: false, key: raw, keyFile: null };
  } else {
    // No key configured: use a persisted one instead of running unprotected
    const keyFile = defaultKeyFile();
    const { key, generated } = loadOrCreateKeyFile(keyFile);
    configuredKey = key;
    authEnabled = true;
    apiKeyStatus = { enabled: true, generated, key, keyFile };
  }
  return apiKeyStatus;
}

export function isAuthEnabled(): boolean {
  return authEnabled;
}

let configuredAdminKey: string | null = null;

/**
 * Initialize the optional admin key (PROXY_ADMIN_KEY).
 * Falls back to the regular API key when no dedicated admin key is set.
 * Returns the same shape as initApiKey for startup logging.
 */
export function initAdminKey(): { configured: boolean; fallback: boolean } {
  const raw = process.env.PROXY_ADMIN_KEY?.trim();
  if (raw) {
    configuredAdminKey = raw;
    return { configured: true, fallback: false };
  }
  return { configured: false, fallback: true };
}

/**
 * Express middleware for /admin/* routes.
 * Requires PROXY_ADMIN_KEY; if unset, the regular PROXY_API_KEY is accepted.
 * If neither exists, admin routes are locked (403).
 */
export function adminAuth(
  req: Request,
  res: Response,
  next: NextFunction
): void {
  const effective = configuredAdminKey || configuredKey;

  if (!effective) {
    res.status(403).json({
      error: {
        message:
          "Admin endpoints are locked. Set PROXY_ADMIN_KEY (or PROXY_API_KEY) to enable them.",
        type: "invalid_request_error",
        code: "admin_locked",
      },
    });
    return;
  }

  const header = req.headers.authorization;
  const token = header?.startsWith("Bearer ") ? header.slice(7).trim() : null;

  if (!token || !safeEqual(token, effective)) {
    res.status(401).json({
      error: {
        message: "Invalid admin key.",
        type: "invalid_request_error",
        code: "invalid_admin_key",
      },
    });
    return;
  }

  next();
}

/**
 * Constant-time string comparison to avoid timing attacks.
 */
function safeEqual(a: string, b: string): boolean {
  const bufA = Buffer.from(a, "utf8");
  const bufB = Buffer.from(b, "utf8");
  if (bufA.length !== bufB.length) {
    return false;
  }
  return timingSafeEqual(bufA, bufB);
}

/**
 * Express middleware enforcing the API key on all routes except /health.
 */
export function apiKeyAuth(
  req: Request,
  res: Response,
  next: NextFunction
): void {
  if (!authEnabled) {
    next();
    return;
  }

  // Health check stays public (uptime monitors, EasyPanel checks)
  // Admin routes handle their own (stricter) auth via adminAuth
  if (req.path === "/health" || req.path.startsWith("/admin")) {
    next();
    return;
  }

  const header = req.headers.authorization;
  const token = header?.startsWith("Bearer ") ? header.slice(7).trim() : null;

  // A missing configured key while auth is on rejects everything (fail closed)
  if (!token || !configuredKey || !safeEqual(token, configuredKey)) {
    res.status(401).json({
      error: {
        message:
          "Invalid or missing API key. Provide it as 'Authorization: Bearer <key>'.",
        type: "invalid_request_error",
        code: "invalid_api_key",
      },
    });
    return;
  }

  next();
}
